Net/ThemeName "Adwaita-dark"
Net/IconThemeName "kora"
Gtk/CursorThemeName "Bibata-Modern-Ice"
Gtk/CursorThemeSize 24
Gtk/FontName "Fira Sans SemiBold 11"
Net/EnableEventSounds 1
EnableInputFeedbackSounds 0
Xft/Antialias 1
Xft/Hinting 1
Xft/HintStyle "hintfull"
Xft/RGBA "rgb"
