cursor #d9e7d0
cursor_text_color #b9ccaf

foreground            #d9e7d0
background            #0c1609
selection_foreground  #013a00
selection_background  #68e054
url_color             #eaffde

# black
color8   #d9e7d0
color0   #4c4c4c

# red
color1   #ffb4ab
color9   #c49ea0

# green
color2   #d9e7d0
color10  #9ec49f

# yellow
color3   #aca98a
color11  #c4c19e

# blue
/* color4  #8f8aac */
color4  #eaffde
color12 #a39ec4

# magenta
color5   #ffb4ab
color13  #c49ec4

# cyan
color6   #d9e7d0
color14  #9ec3c4

# white
color15   #e7e7e7
color7  #f0f0f0