# Generated by matugen from ~/.config/matugen/templates/i3lock-colors.sh --
# do not edit by hand. Sourced by ~/.config/i3/scripts/lock.sh; RRGGBB, no '#'.
LOCK_BACKGROUND=101418
# LOCK_PRIMARY/LOCK_ON_PRIMARY: the fixed xcloud green (matugen custom colour `xcloud`)
LOCK_PRIMARY=00ff00
LOCK_ON_PRIMARY=015000
LOCK_ON_SURFACE=e0e2e8
LOCK_ERROR=ffb4ab
