# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e0e2e8"

# Title color for boxes
theme[title]="#9cd0ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#adcae6"

# Background color of selected item in processes box
theme[selected_bg]="#9cd0ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#003351"

# Color of inactive/disabled text
theme[inactive_fg]="#bfc7d1"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#eeb7ff"

# Cpu box outline color
theme[cpu_box]="#8a919b"

# Memory/disks box outline color
theme[mem_box]="#8a919b"

# Net up/down box outline color
theme[net_box]="#8a919b"

# Processes box outline color
theme[proc_box]="#8a919b"

# Box divider line and small boxes line color
theme[div_line]="#404850"

# Temperature graph colors
theme[temp_start]="#adcae6"
theme[temp_mid]="#9cd0ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#adcae6"
theme[cpu_mid]="#9cd0ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#adcae6"
theme[free_mid]=""
theme[free_end]="#2d4961"

# Mem/Disk cached meter
theme[cached_start]="#eeb7ff"
theme[cached_mid]=""
theme[cached_end]="#d798ec"

# Mem/Disk available meter
theme[available_start]="#9cd0ff"
theme[available_mid]=""
theme[available_end]="#64b6f7"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#adcae6"
theme[download_mid]="#9cd0ff"
theme[download_end]="#eeb7ff"

# Upload graph colors
theme[upload_start]="#adcae6"
theme[upload_mid]="#9cd0ff"
theme[upload_end]="#eeb7ff"