# Generated by matugen from ~/.config/matugen/templates/i3lock-colors.sh --
# do not edit by hand. Sourced by ~/.config/i3/scripts/lock.sh; RRGGBB, no '#'.
LOCK_BACKGROUND={{colors.background.default.hex_stripped}}
# LOCK_PRIMARY/LOCK_ON_PRIMARY: the fixed xcloud green (matugen custom colour `xcloud`)
LOCK_PRIMARY={{colors.xcloud_source.default.hex_stripped}}
LOCK_ON_PRIMARY={{colors.on_xcloud_container.default.hex_stripped}}
LOCK_ON_SURFACE={{colors.on_surface.default.hex_stripped}}
LOCK_ERROR={{colors.error.default.hex_stripped}}
